# Generated by Django 3.2.4 on 2021-06-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_employee_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='about',
            new_name='profile',
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/', verbose_name='Profile Picture'),
        ),
    ]
